### ISSUE TITLE
feat: implement "recent recipes" list

### ISSUE THREAD

**Issue by JoarHansson** [sirisayshello/recipe-declutter#111]
I think this can be solved by updating the Recipe model and implementing something like this example with "updatedAt" from the [prisma docs](https://www.prisma.io/docs/orm/prisma-schema/data-model/models):

```PRISMA
model Post {
  id         Int        @id @default(autoincrement())
  createdAt  DateTime   @default(now())
  updatedAt  DateTime   @updatedAt
  title      String
  published  Boolean    @default(false)
  author     User       @relation(fields: [authorId], references: [id])
  authorId   Int
  categories Category[]
}
```

If we find a way to store the "viewedAt" value instead, we can update the "recent recipes" list to sort by this value.

**Comment by JoarHansson** [comment]
After discussion we decided that createdAt and/or updatedAt will work. No need to try to implement "viewedAt".

**Comment by sirisayshello** [comment]
Should we also implement a limit for recipes shown? 10 latest?

**Comment by JoarHansson** [comment]
> Should we also implement a limit for recipes shown? 10 latest?

Good idea
