### ISSUE TITLE
bug: signout redirect

### ISSUE THREAD

**Issue by JoarHansson** [sirisayshello/recipe-declutter#140]
the redirect is now hardcoded to localhost:3000

**Comment by sirisayshello** [comment]
This is the sign out function in `SignOutButton.tsx`, where is this issue located?

```js
  const onSignOut = () => {
    signOut({ callbackUrl: "/" });
  };
```

**Comment by JoarHansson** [comment]
Not sure! All i know is when pressing the sign out button on the deployed site, you are redirected to http://localhost:3000/
