### ISSUE TITLE
feat: add tags to recipe

### ISSUE THREAD

**Issue by juliasophieg** [sirisayshello/recipe-declutter#161]
**Suggestion:**
Make a table for tags, with a column called userId that is nullable. Fill it with default tags, ("Dinner", "Lunch", "Dessert" etc) and set those to userId = null. If a user adds a new tag ("ChristmasParty2024" for example), this tag gets their userId and is only accessible to them.

**Question:**
Should tags related to a recipe be saved as a string array within the recipe, or should we use a many to many table (recipe_tags)? A string array is easy and might be enough for our needs, but lacks flexibility and scalability. When searching for all recipes with a certain tag ("Find all recipes with the tag "Dinner" for example) the many to many table approach might be more suitable?

**Problem:**
There will probably be duplicates in the tables. For example if two people create their own "ChristmasParty2024" tag, each will have their own tag entry in the tags table with a unique userId, but the tag name will be the same.

**Comment by JoarHansson** [comment]
I think a many-to-many relation is a good idea!

**Comment by sirisayshello** [comment]
I like the many to many as well! And checking for duplicates seems like a good idea, maybe using `ON CONFLICT DO NOTHING`?

Do we want more info, or just like this:

**Tags**
```sql
CREATE TABLE Tags (
    tag_id SERIAL PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL 
);
```

**RecipeTags** (join table)
```sql
CREATE TABLE RecipeTags (
    recipe_id INT REFERENCES Recipes(recipe_id) ON DELETE CASCADE,
    tag_id INT REFERENCES Tags(tag_id) ON DELETE CASCADE,
    PRIMARY KEY (recipe_id, tag_id) 
);
```
