### ISSUE TITLE
feat: consistent styling for dropdown menus

### ISSUE THREAD

**Issue by juliasophieg** [sirisayshello/recipe-declutter#187]

**Comment by sirisayshello** [comment]
A suggestion is making both burger menu and account menu cover the screen for smaller devices, opening from left and right. On bigger devices the burger could disappear and links be displayed in the navbar, and the account menu a drawer opening from right. 

I think [ICA](https://www.ica.se/)  is a good example for this approach.

Did some quick research and think a dropdown menu is suitable if the links contain more links, like on print screen below.

![Screenshot 2024-11-12 at 12 29 41](https://github.com/user-attachments/assets/8e2149f8-27d0-426a-b2cc-b193bac03bbf)
