### ISSUE TITLE
bug: loading, success/error and recipe result is hidden behind sign up modal

### ISSUE THREAD

**Issue by juliasophieg** [sirisayshello/recipe-declutter#188]
Not really a bug but when scraping as a guest user the loading, success/error messages and the actual result is hidden behind the sign up modal:

1. While decluttering
2. Result

<img width="334" alt="Screenshot 2024-11-11 at 09 34 38" src="https://github.com/user-attachments/assets/49e000f6-3612-430e-a0ca-f144cbe672e0">
<img width="334" alt="Screenshot 2024-11-11 at 09 35 00" src="https://github.com/user-attachments/assets/5b26a7f8-7a84-44d6-bfda-2f6fa20a23a4">

**Comment by sirisayshello** [comment]
What do you think about refactor the pop up banner to not be a pop up but just a section on the landing page? Then it will no longer be in the way of the result, either keeping it underneath or removing it on result.
