### ISSUE TITLE
feat: change trash icons to kebab icon in editRecipe 

### ISSUE THREAD

**Issue by sirisayshello** [sirisayshello/recipe-declutter#200]
- In edit recipe page and `EditIngredientAndInstructionsList.tsx` having very many trashcans looks a bit wonky, suggests replacing them with kebab (or as it is also called, _more options icon_) in right section of input field.
- Also suggest doing the same for deleting recipe button.

So the steps for deleting list item or recipe would be - options, delete. Instead of just - delete.
This would also minimise risk of accidentally deleting something.

<img width="324" alt="Screenshot 2024-11-13 at 22 36 42" src="https://github.com/user-attachments/assets/af1ab3b0-3ee4-4e9a-a22a-d45a65c45421">
<img width="325" alt="Screenshot 2024-11-13 at 22 32 06" src="https://github.com/user-attachments/assets/4cc4f8ac-d543-4ee8-b46f-2e454f0b0b0a">

**Comment by sirisayshello** [comment]
Added medium prio label, feel free to disagree

**Comment by juliasophieg** [comment]
Try usin IconMenu as drag-drop icon?
