### ISSUE TITLE
feat: add success notification on updating recipe

### ISSUE THREAD

**Issue by sirisayshello** [sirisayshello/recipe-declutter#207]
- In `EditRecipeForm.tsx` we should show some feedback on changes saved / recipe updated, suggest using notifications the same way we do when decluttering recipe.

**Comment by JoarHansson** [comment]
Duplicate issue (I guess): #182 - This one with medium prio. 

I agree it's quite high prio though...

**Comment by sirisayshello** [comment]
Oh good I missed that one! I'll close this issue and perhaps update to  #182 to high prio

**Comment by sirisayshello** [comment]
Oh good I missed that one! I'll close this issue and perhaps update to  #182 to high prio
